{
  browser = [
    "text/html"
    "x-scheme-handler/http"
    "x-scheme-handler/https"
    "x-scheme-handler/ftp"
    "x-scheme-handler/about"
    "x-scheme-handler/unknown"
    "application/x-extension-htm"
    "application/x-extension-html"
    "application/x-extension-shtml"
    "application/xhtml+xml"
    "application/x-extension-xhtml"
    "application/x-extension-xht"
    "application/json"
  ];

  pdf = [ "application/pdf" ];

  audio = [
    "audio/3gpp"
    "audio/3gpp2"
    "audio/aac"
    "audio/ac3"
    "audio/flac"
    "audio/midi"
    "audio/mp2"
    "audio/mp3"
    "audio/mp4"
    "audio/mpeg"
    "audio/mpeg3"
    "audio/ogg"
    "audio/opus"
    "audio/wav"
    "audio/webm"
    "audio/x-aiff"
    "audio/x-flac"
    "audio/x-m4a"
    "audio/x-mp3"
    "audio/x-ms-wma"
    "audio/x-wav"
    "audio/x-vorbis+ogg"
  ];

  video = [
    "video/3gpp"
    "video/3gpp2"
    "video/avi"
    "video/divx"
    "video/mp2t"
    "video/mp4"
    "video/mp4v-es"
    "video/mpeg"
    "video/mpeg4"
    "video/ogg"
    "video/quicktime"
    "video/webm"
    "video/x-flv"
    "video/x-matroska"
    "video/x-ms-asf"
    "video/x-ms-wmv"
    "video/x-msvideo"
    "video/x-theora+ogg"
    "video/x-ogm+ogg"
  ];

  image = [
    "image/avif"
    "image/bmp"
    "image/gif"
    "image/heic"
    "image/heif"
    "image/ico"
    "image/jpeg"
    "image/jxl"
    "image/png"
    "image/svg+xml"
    "image/tiff"
    "image/webp"
    "image/x-xbitmap"
    "image/x-xpixmap"
    "image/x-tga"
    "image/x-portable-bitmap"
    "image/x-portable-graymap"
    "image/x-portable-pixmap"
    "image/x-portable-anymap"
    "image/x-ms-bmp"
  ];
}
